[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']

[invariant]
fail_on_revert = false
runs = 1215
depth = 23

# See more config options https://github.com/foundry-rs/foundry/tree/master/config